return {
  misc = {
    dots = "󰇘",
  },
  ft = {
    octo = "",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    -- Error = " ",
    Error = "",
    Warn = " ",
    -- Warn = "",
    -- Hint = ""
    Hint = "",
    -- Info = " ",
    Info = "",
  },
  git = {
    commit = "󰜘 ", -- used by git log
    staged = "●", -- staged changes. always overrides the type icons
    added = "",
    deleted = "",
    ignored = " ",
    modified = "○",
    renamed = "",
    unmerged = " ",
    untracked = "?",
  },
  kinds = {
    File = " ",
    Folder = " ",
    -- Array = " ",
    -- Boolean = "󰨙 ",
    -- Class = " ",
    -- Codeium = "󰘦 ",
    -- Color = " ",
    -- Control = " ",
    -- Collapsed = " ",
    -- Constant = "󰏿 ",
    -- Constructor = " ",
    -- Copilot = " ",
    -- Enum = " ",
    -- EnumMember = " ",
    -- Event = " ",
    -- Field = " ",
    -- Function = "󰊕 ",
    -- Interface = " ",
    -- Key = " ",
    -- Keyword = " ",
    -- Method = "󰊕 ",
    -- Module = " ",
    -- Namespace = "󰦮 ",
    -- Null = " ",
    -- Number = "󰎠 ",
    -- Object = " ",
    -- Operator = " ",
    -- Package = " ",
    -- Property = " ",
    -- Reference = " ",
    -- Snippet = "󱄽 ",
    -- String = " ",
    -- Struct = "󰆼 ",
    -- Supermaven = " ",
    -- TabNine = "󰏚 ",
    -- Text = " ",
    -- TypeParameter = " ",
    -- Unit = " ",
    -- Value = " ",
    -- Variable = "󰀫 ",
  },
}
